spring:
  application:
    name: Auth Service

user-service:
  url: http://localhost:8080/api/v1/users/auth/validate

security:
  jwt:
    key: ${JWT_SECRET}
    access-token-expiration: 14400000
    refresh-token-expiration: 604800000

app:
  cors:
    allowed-origins:
      - http://localhost:5173

server:
  port: 8081
