services:
  postgres:
    image: postgres:15
    container_name: localpos-db
    environment:
      POSTGRES_DB: localpos_db
      POSTGRES_USER: localpos_user
      POSTGRES_PASSWORD: localpos_pass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  pgdata:
