version: "3.8"
services:
  localpos-user-service:
    build:
      context: ../../localpos-user-service
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
  # Agregar servicios similares para otros microservicios
