spring:
  application:
    name: User Service

  main:
    allow-bean-definition-overriding: true

  datasource:
    url: jdbc:postgresql://localhost:5432/localpos_db
    username: localpos_user
    password: localpos_pass
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

app:
  locale: en

security:
  jwt:
    secret: ${JWT_SECRET}
    expiration-ms: 900000
