spring:
  application:
    name: Product Service

  datasource:
    url: jdbc:postgresql://localhost:5432/localpos_user_db
    username: localpos_user
    password: localpos_pass
    driver-class-name: org.postgresql.Driver
